# Generated by Django 5.1.6 on 2025-08-01 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/')),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'None')], default='N', max_length=7)),
                ('phone_number', models.CharField(blank=True, default='', max_length=11)),
                ('password_reset_token', models.CharField(blank=True, default='', max_length=60)),
                ('password_reset_expire', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('specialist', 'Specialist')], default='patient', max_length=10)),
                ('bio', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('experience', models.PositiveIntegerField(blank=True, help_text='Years of experience', null=True)),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('specialty', models.CharField(blank=True, choices=[('اخصائي نفسية', 'اخصائي نفسية'), ('استشاري علاقات اسرية', 'استشاري علاقات اسرية'), ('اخصائي التوحد', 'اخصائي التوحد'), ('اخصائي ADHD', 'اخصائي ADHD'), ('مشورة سرية', 'مشورة سرية'), ('اخصائي تربوي للاطفال', 'اخصائي تربوي للاطفال'), ('اخصائي نفسي', 'اخصائي نفسي'), ('اخصائي مشاكل اسرية', 'اخصائي مشاكل اسرية'), ('اخصائي علاج الادمان', 'اخصائي علاج الادمان'), ('استشاري علاقات زوجية', 'استشاري علاقات زوجية'), ('اخصائي صدمات نفسية', 'اخصائي صدمات نفسية'), ('اخصائي نفسي للاطفال', 'اخصائي نفسي للاطفال'), ('اخصائي سلوك', 'اخصائي سلوك'), ('اخصائي العلاج الجماعي', 'اخصائي العلاج الجماعي'), ('اخصائي اكتئاب وقلق', 'اخصائي اكتئاب وقلق'), ('اخصائي اضطرابات الشخصية', 'اخصائي اضطرابات الشخصية'), ('اخصائي علاج وظيفي', 'اخصائي علاج وظيفي'), ('اخصائي نطق وتخاطب', 'اخصائي نطق وتخاطب'), ('مدرب حياة', 'مدرب حياة'), ('other', 'Other')], max_length=50)),
                ('extra_specialty', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
