# Generated by Django 5.1.6 on 2025-08-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='experience',
            new_name='years_of_experience',
        ),
    ]
