# Generated by Django 5.1.6 on 2025-08-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_experience_profile_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('None', 'None')], default='None', max_length=7),
        ),
    ]
