# Generated by Django 5.1.6 on 2025-08-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password_reset_token',
        ),
        migrations.AddField(
            model_name='profile',
            name='password_reset_otp',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
