# Generated by Django 5.1.6 on 2025-08-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profile_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default_profile.jpg', upload_to='profile_pics/'),
        ),
    ]
