# Generated by Django 5.1.6 on 2025-08-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_end_time_profile_start_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='specialty',
            new_name='speciality',
        ),
    ]
