# Generated by Django 5.1.6 on 2025-08-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='in_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
