# Generated by Django 5.1.6 on 2025-10-18 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_coursereview'),
        ('programs', '0004_alter_course_category_alter_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='programs.course'),
        ),
    ]
