# Generated by Django 5.1.6 on 2025-10-24 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_status_statusreply_seenstatus_statuslikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likecomments',
            name='liked',
        ),
    ]
