# Generated by Django 5.1.6 on 2025-10-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_course_coursevideo_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
