# Generated by Django 5.1.6 on 2025-10-18 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_specialty_profile_speciality'),
        ('programs', '0003_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(help_text='Only specialists can create courses.', limit_choices_to={'role': 'specialist'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='account.profile'),
        ),
    ]
