# Generated by Django 5.1.6 on 2025-12-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_programcategory_freeprogram_programsession_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programsession',
            old_name='video_file',
            new_name='video',
        ),
        migrations.RemoveField(
            model_name='programsession',
            name='video_url',
        ),
    ]
