# Generated by Django 5.1.6 on 2025-12-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_rename_video_file_programsession_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programcategory',
            old_name='title',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='programcategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='programcategory',
            name='slug',
        ),
    ]
