# Generated by Django 5.1.6 on 2025-12-25 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_specialty_profile_speciality'),
        ('programs', '0007_rename_title_programcategory_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='freeprogram',
            name='user',
            field=models.ForeignKey(help_text='The specialist who created this program', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='account.profile'),
        ),
        migrations.AlterField(
            model_name='musiccard',
            name='album_cover',
            field=models.ImageField(blank=True, default='music_covers/music_cover.png', null=True, upload_to='music_covers/'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
